# -*- coding: utf-8 -*-
"""Module3_Clinical Note Generation_&_ICD-10 Coding Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkIgPydorMFQC_SXTWZzhp85mDd6YJNh

# 🏥 Module 3 — Clinical Note Generation & ICD-10 Coding Automation

This notebook demonstrates **Module 3** of the healthcare AI project:  
➡️ automated **clinical note generation** using generative AI,  
➡️ **ICD-10 code automation** for standardized diagnosis coding, and  
➡️ integration of **enhanced X-ray images** with patient metadata.

The outcome of this module is a **unified dataset** that combines:
- Patient demographics and hospital data  
- AI-generated clinical notes  
- Predicted ICD-10 diagnostic codes  
- Linked enhanced X-ray image paths  

This unified dataset forms the foundation for **Module 4 (UI visualization)**.
"""

!pip install transformers accelerate torch pandas -q
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

"""## 🧩 Loading and Preparing Patient Data

We begin by loading the base healthcare dataset that contains patient details,  
medical condition, and diagnostic test results.  

This data serves as the input for generating structured **clinical notes** in the next step.

"""

# Load your prepared dataset
file_path = "/content/healthcare_xray_data.xlsx"   # <-- update if needed
df = pd.read_excel(file_path)

# Quick check
df.head(2)

"""## 🩺 Clinical Note Generation  

In this step, we use a **Generative AI language model (BioGPT)** to generate realistic doctor-style clinical notes.  
Each note is created from structured patient information such as age, gender, medical condition, and the AI-generated X-ray caption.  

The model converts tabular EHR data into free-text summaries that resemble how clinicians write discharge notes or examination reports.  
The generated notes are saved as a new column called `clinical_note`.
"""

!pip install sacremoses -q

model_name = "microsoft/BioGPT-Large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, dtype=torch.float16, device_map="auto")

"""### 🧩 Prepare the AI Prompt
We’ll combine structured patient data into a single prompt string for each record.
"""

# Function to prepare structured, professional prompt
def build_prompt(row):
    return (f"Clinical note of the patient:\n"
            f"Name: {row['Name']}\n"
            f"Age: {row['Age']}\n"
            f"Gender: {row['Gender']}\n"
            f"Blood Type: {row['Blood Type']}\n"
            f"Medical Condition: {row['Medical Condition']}\n"
            f"Admission Type: {row['Admission Type']}\n"
            f"Date of Admission: {row['Date of Admission']}\n"
            f"Discharge Date: {row['Discharge Date']}\n"
            f"Doctor: {row['Doctor']}\n"
            f"Hospital: {row['Hospital']}\n"
            f"Medications: {row['Medication']}\n"
            f"Test Results: {row['Test Results']}\n"
            f"X-ray Findings: {row['xray_caption']}\n"
            f"Provide the note in the style of a doctor's summary including clinical interpretation, assessment, and plan.\n"
           )

# Apply prompt preparation
df["prompt"] = df.apply(build_prompt, axis=1)
print("✅ Prompts prepared for", len(df), "records")
df[["Name", "prompt"]].head(2)

# ==============================================================
# Define Clinical Note Generation Function
# ==============================================================

import re

# Text cleanup (to remove unwanted tokens or repeated words)
def clean_note_output(text):
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"^(.*?)🩺", "🩺", text, flags=re.DOTALL)
    text = re.sub(r'^(Here is|Below is).*?:', '', text, flags=re.IGNORECASE)
    return text.strip()

# Generation function
def generate_note(prompt):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(model.device)
    output_tokens = model.generate(
        **inputs,
        max_length=300,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )
    note = tokenizer.decode(output_tokens[0], skip_special_tokens=True)
    return clean_note_output(note)

import re

def clean_note_output(text):
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"^(.*?)🩺", "🩺", text, flags=re.DOTALL)
    text = re.sub(r'^(Here is|Below is).*?:', '', text, flags=re.IGNORECASE)
    # Remove the specific character '▃' and potentially other similar artifacts
    text = re.sub(r'[▃]+', '', text)
    return text.strip()

# ==============================================================
# Test Note Generation for 5 Samples
# ==============================================================

df_sample = df.head(5).copy()
print("⏳ Generating notes for 5 test records...")

df_sample["clinical_note"] = df_sample["prompt"].apply(generate_note)

print("✅ Generated notes for 5 patients!")
df_sample[["Name", "clinical_note"]]

"""### ✅ Result of Clinical Note Generation  

The dataset now includes a new column `clinical_note` containing automatically generated summaries.  
These notes provide context for each patient’s case and will serve as the textual input for ICD-10 code prediction in the next step.  
A sample preview confirms that the generated text follows a consistent, professional medical format.

"""

# ==============================================================
# Full Clinical Note Generation (500 Records)
# ==============================================================

df_full = df.head(500).copy()
print("⏳ Generating structured notes for 500 patients...")

from tqdm import tqdm
tqdm.pandas()

df_full["clinical_note"] = df_full["prompt"].progress_apply(generate_note)

print("✅ Completed generation for 500 patients!")

# Save to CSV
output_path = "/content/healthcare_xray_data_with_structured_notes_biogpt.csv"
df_full.to_csv(output_path, index=False)
print("📁 Results saved to:", output_path)

file_path = "/content/healthcare_xray_data_with_structured_notes_biogpt.csv"   # update path if needed
df = pd.read_csv(file_path)

# Show sample
df.head(3)

"""## 💊 ICD-10 Coding Automation  

After generating the clinical notes, the next task is to automatically assign **ICD-10 codes**.  
Instead of manual lookup, we use a **publicly available Hugging Face model** trained for medical text-to-ICD-10 prediction (`AkshatSurolia/ICD-10-Code-Prediction`).  

The model reads each clinical note and outputs the corresponding ICD-10 code and description.  
These predictions are stored in a new column `Predicted_ICD`.

"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_name = "AkshatSurolia/ICD-10-Code-Prediction"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

# ==============================================================
# Import libraries and load Hugging Face model
# ==============================================================

!pip install transformers torch tqdm --quiet

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm
import pandas as pd

# Load ICD-10 prediction model
model_name = "AkshatSurolia/ICD-10-Code-Prediction"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
model.eval()

print("✅ Model loaded successfully:", model_name)

# ==============================================================
# Load dataset containing generated clinical notes
# ==============================================================

# Path to your dataset (update as per your saved CSV)
input_path = "/content/healthcare_xray_data_with_structured_notes_biogpt.csv"
df = pd.read_csv(input_path)

print("✅ Dataset loaded successfully with", len(df), "records")
df.head(2)

# ==============================================================
# Prepare ICD-10 classification input prompt
# ==============================================================

# Combine relevant text info for ICD prediction
def build_icd_prompt(row):
    prompt = (
        f"Patient Name: {row['Name']}. "
        f"Condition: {row['Medical Condition']}. "
        f"Clinical Note: {row['clinical_note']}"
    )
    # Apply the cleaning function to the generated prompt
    return clean_note_output(prompt)


df["icd_prompt"] = df.apply(build_icd_prompt, axis=1)
print("✅ ICD prompts prepared")
df[["Name", "icd_prompt"]].head(2)

# ==============================================================
# Predict ICD-10 codes for patient records
# ==============================================================

def generate_icd_code(prompt):
    # Tokenize input
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    logits = outputs.logits
    predicted_class_id = torch.argmax(logits, dim=1).item()
    predicted_code = model.config.id2label[predicted_class_id]
    return predicted_code

# Test on a small subset first (e.g., 10 rows)
df_sample = df.sample(10, random_state=42).copy()

for i, row in tqdm(df_sample.iterrows(), total=len(df_sample)):
    df_sample.loc[i, "Predicted_ICD"] = generate_icd_code(row["icd_prompt"])

print("✅ ICD-10 code prediction complete for 10 samples")
df_sample[["Name", "Medical Condition", "Predicted_ICD"]]

# ==============================================================
# Predict ICD codes for all records (Full Run)
# ==============================================================

df_full = df.copy()

for i, row in tqdm(df_full.iterrows(), total=len(df_full)):
    df_full.loc[i, "Predicted_ICD"] = generate_icd_code(row["icd_prompt"])

print("✅ ICD prediction complete for entire dataset")

# Keep only relevant columns
df_final = df_full[["Name", "Medical Condition", "Predicted_ICD"]]
df_final.head(5)

"""### ✅ Result of ICD-10 Automation  

Each record now contains an automatically generated ICD-10 code with its description.  
This completes the automation of routine clinical documentation and coding tasks using GenAI.  
The enriched dataset (`data_with_predicted_icd.csv`) is ready for integration with patient images in the next step.

"""

# ==============================================================
# Save output file with predicted ICD codes
# ==============================================================

output_path = "/content/data_with_predicted_icd.csv"
df_final.to_csv(output_path, index=False)

print(f"📁 Saved final ICD-coded dataset to: {output_path}")
print("✅ Columns:", df_final.columns.tolist())

"""##  Merging ICD Codes with Patient Records

The predicted ICD-10 codes are then merged back into the original dataset,  
creating a single comprehensive table containing:
- Patient details  
- AI-generated clinical notes  
- Predicted ICD-10 codes  

This merged dataset is stored as **UnifiedDataset.csv** for further processing.

"""

import pandas as pd

# Load both datasets
notes_df = pd.read_csv("/content/healthcare_xray_data_with_structured_notes_biogpt.csv")
icd_df   = pd.read_csv("/content/data_with_predicted_icd.csv")

print("Notes data:", notes_df.shape)
print("ICD data:", icd_df.shape)

# Merge on Name (or patient_id if you used that as key)
merged_df = notes_df.merge(icd_df, on="Name", how="left")

print("✅ Combined dataset shape:", merged_df.shape)
merged_df.head(3)

final_path = "/content/unified_dataset.csv"
merged_df.to_csv(final_path, index=False)
print("📁 Final unified dataset saved at:", final_path)

"""## 🩻 Linking Enhanced X-Ray Images

To provide visual clinical context, we integrate the enhanced X-ray images  
that were previously generated using the **image enhancement model**.

Since the dataset does not have direct patient-to-image mapping,  
the X-ray images are **randomly but uniformly assigned** to patient records.  
This step ensures that each record contains a valid image path for display in Module 4.

The output file **UnifiedDataset_with_images.csv** contains:
- Patient details  
- Generated clinical note  
- Predicted ICD-10 code  
- Linked X-ray image path

"""

import os

# Create the directory if it doesn't exist
output_dir = "/content/enhanced_images/xray_enhanced"
os.makedirs(output_dir, exist_ok=True)

# Unzip the file into the created directory
!unzip -o /content/xray_enhanced.zip -d {output_dir}

import os, random
import pandas as pd

# Load your unified dataset
df = pd.read_csv("/content/unified_dataset.csv")

# Folder containing your enhanced X-ray images
image_folder = "/content/enhanced_images/xray_enhanced/xray_enhanced" # Corrected path

# List all image files
image_files = [f for f in os.listdir(image_folder) if f.lower().endswith(('.png','.jpg','.jpeg'))]

# Randomly assign images to patient records
random.shuffle(image_files)
df["xray_image"] = [os.path.join(image_folder, image_files[i % len(image_files)]) for i in range(len(df))]

# Save the updated dataset
linked_path = "/content/UnifiedDataset_with_images.csv"
df.to_csv(linked_path, index=False)

print("✅ Linked X-ray image paths successfully!")
print("📁 Saved at:", linked_path)
df.head(3)

"""## ✅ Summary of Module 3

**Module 3** successfully demonstrates end-to-end AI automation in healthcare data processing.

### 🔹 Key Achievements
- Generated professional, structured **clinical notes** using pre-trained Gen-AI models  
- Automated **ICD-10 code prediction** based on the generated notes  
- Created a unified dataset integrating all patient, textual, and image data  

### 📦 Final Output File
`UnifiedDataset_with_images.csv`

This file now serves as the single source for:
- Visualization and UI integration in Module 4  
- Report generation and validation  
- Demonstrating the project’s Gen-AI driven clinical intelligence pipeline

---

"""